server:
  port: 9020

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://admin:BmSoft123@localhost:9010/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lidongsheng123/spring-cloud.git
          search-paths: /config-repo/
          username: lidongsheng123
          password: 5f96bd3fddfb1d9874ed87e6e4979c5bba5c1a3e
        health:
          repositories:
            a-hello:
              label: master
              name: hello
              profiles: dev



