server:
  port: 9060
spring:
  application:
    name: hystrix-turbine-mq

  rabbitmq:
    host: 127.0.0.1
    port: 5673
    username: guest
    password: guest


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://admin:BmSoft123@localhost:9010/eureka/

info:
  description: 监控数据聚合


