spring:
  application:
    name: MMS-PROVIDER
  datasource:
    url: jdbc:mysql://www.itkbp.com:5410/transcode_vms?useUnicode=true&characterEncoding=utf-8
    username: transcoder
    password: transcoder^
    druid:
         driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://admin:BmSoft123@localhost:9010/eureka/

mybatis:
  type-aliases-package: com.bmsoft.cloud.transcoder.template.entity
  mapper-locations: classpath:mybaties/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
