server:
  port: 9411

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://admin:BmSoft123@localhost:9010/eureka/
#zipkin:
  #storage:
    #type: elasticsearch
    #elasticsearch:
      #cluster: elasticsearch
      #hosts: http://localhost:9200
      #index: zipkin
      #index-shards: 5
      #index-replicas: 1

