server:
  port: 9010
# 安全认证的配置  
security:  
  basic:  
    enabled: true  
  user:  
    name: admin  # 用户名  
    password: BmSoft123   # 用户密码     
spring:
  application:
    #name必须一样，不然高可用会导致unavailable-replicas
    name: cloud-register-center
eureka:
  instance:
    hostname: cloud-register-center1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:BmSoft123@cloud-register-center2:9010/eureka/